server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nenya?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  redis:
    database: 8
    host: 152.136.135.131
    port: 6379
    password: g0w?oc|[6qTyy!bpkieDio\giuiwixcd
    timeout: 1000
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
#日志配置
logging:
  config: classpath:logback-spring.xml
